In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [48]:
data_g=pd.read_excel('C:/Users/user/Desktop/psl/fault_feature_jirak.xls')
data_l=pd.read_excel('C:/Users/user/Desktop/psl/fault_feature_seongan.xls')
data_n=pd.read_excel('C:/Users/user/Desktop/psl/feature_normal.xls')

data = pd.concat([data_g,data_l,data_n])

target = []

for idx, row in data.iterrows():
    if row['type'] == 0:
        target.append(0)
    elif row['type'] == 1 or row['type'] == 2 or row['type'] == 3:
        target.append(1)
    else:
        target.append(2)

data['type'] = target

X1 = data.filter(['target', 'type','m'])
X=data.drop(['target', 'type','m'],axis=1)
y=X1.filter(['type'])

X_tn, X_te, y_tn, y_te=train_test_split(X,y,test_size=0.2,shuffle=True, random_state=1)
print(X_tn.shape)
print(y_tn.shape)
print(X_te.shape)
print(y_te.shape)

(1680, 48)
(1680, 1)
(420, 48)
(420, 1)


In [49]:
# 랜덤포레스트 학습
clf_rf = RandomForestClassifier(max_depth=2, 
                                random_state=0)
clf_rf.fit(X_tn, y_tn)

# 예측
pred_rf = clf_rf.predict(X_te)
print(pred_rf)

# 정확도
accuracy = accuracy_score(y_te, pred_rf)
print(accuracy)

# confusion matrix 확인 
conf_matrix = confusion_matrix(y_te, pred_rf)
print(conf_matrix)

# 분류 레포트 확인
class_report = classification_report(y_te, pred_rf)
print(class_report)

C:\Users\user\AppData\Local\Temp\ipykernel_22076\3944578246.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf_rf.fit(X_tn, y_tn)


[0 2 1 1 0 2 0 0 2 1 2 2 2 1 2 0 0 1 2 2 0 1 1 2 2 0 1 1 0 0 1 2 0 1 1 2 0
 0 0 0 1 1 2 0 2 1 1 0 2 2 2 0 1 0 0 2 1 0 1 0 2 2 0 1 2 0 0 0 0 2 0 1 0 0
 0 0 1 2 2 0 0 0 0 0 1 2 2 2 0 0 0 0 1 2 0 0 1 0 0 2 1 2 0 1 1 0 0 0 1 0 0
 1 2 1 1 2 1 2 2 2 0 1 0 0 0 1 2 0 0 2 0 2 2 0 1 1 0 2 0 2 2 1 1 1 2 0 1 1
 2 2 0 2 0 1 1 1 2 2 1 0 1 1 0 2 0 2 0 2 2 2 0 0 2 1 1 2 1 0 1 0 0 1 0 1 1
 1 2 1 0 2 2 0 2 1 0 1 1 2 1 2 0 1 2 1 2 2 2 2 0 0 0 2 0 2 0 0 2 2 0 2 1 0
 2 0 0 0 1 2 0 0 2 0 2 2 0 0 0 1 2 0 1 0 1 0 0 2 2 2 1 2 2 2 2 0 2 0 0 2 0
 0 0 0 1 2 1 0 1 0 1 1 1 0 2 2 0 0 2 1 2 0 0 0 0 2 2 0 1 1 0 2 1 0 1 2 2 0
 1 1 0 0 2 2 1 0 2 1 1 1 1 1 0 2 1 2 0 0 1 2 2 0 2 1 1 1 2 1 0 1 1 0 0 2 2
 2 2 0 0 1 1 2 1 2 0 1 1 0 1 1 0 0 2 2 1 2 2 1 1 1 0 1 2 0 0 0 2 0 1 2 0 1
 2 2 0 1 1 0 0 1 0 1 0 1 0 2 1 1 0 0 1 0 0 2 1 1 2 2 2 0 0 1 0 2 1 2 2 0 1
 2 1 1 0 1 1 1 0 1 2 0 1 0]
0.8952380952380953
[[134   1   0]
 [ 18 115   4]
 [  7  14 127]]
              precision    recall  f1-score   support

           0       0.84    